name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Web Server Folder
        shell: powershell
        run: |
          # Define la ruta de destino en tu servidor web (ej. IIS o Nginx en Windows)
          $DestinationPath = "C:\inetpub\wwwroot\3k.institucional"
          
          # Asegurarse de que el directorio de destino existe
          if (!(Test-Path -Path $DestinationPath)) {
              New-Item -ItemType Directory -Force -Path $DestinationPath
          }
          
          # Copiar los nuevos archivos compilados
          Copy-Item -Path .\dist\* -Destination $DestinationPath -Recurse -Force
