name: Deploy 3KODE Institucional

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Despliegue Automático en VPS Donweb
    runs-on: ubuntu-latest

    steps:
      - name: Conectar por SSH y actualizar contenedor Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/app/3k.Institucional
            git pull origin main
            cd /root/app
            docker compose up -d --build web
            docker image prune -f
